"""initialisation de mon programme

Revision ID: 3d006336ee80
Revises: 
Create Date: 2025-08-21 03:38:45.702781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d006336ee80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrateurs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('super_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alcool_test_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datte', sa.DateTime(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alcool_test_model_id'), 'alcool_test_model', ['id'], unique=False)
    op.create_table('personnes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('postnom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_personnes_id'), 'personnes', ['id'], unique=False)
    op.create_table('chauffeurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_permis', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['personnes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_permis')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('personne_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personne_id'], ['personnes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('historiques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chauffeur_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('jour_heure', sa.DateTime(), nullable=False),
    sa.Column('person_info', sa.String(length=255), nullable=False),
    sa.Column('alcool_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['chauffeurs.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historiques_id'), 'historiques', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historiques_id'), table_name='historiques')
    op.drop_table('historiques')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_table('chauffeurs')
    op.drop_index(op.f('ix_personnes_id'), table_name='personnes')
    op.drop_table('personnes')
    op.drop_index(op.f('ix_alcool_test_model_id'), table_name='alcool_test_model')
    op.drop_table('alcool_test_model')
    op.drop_table('administrateurs')
    # ### end Alembic commands ###
