"""mise à jour de la base

Revision ID: 15d268785937
Revises: d3aa437189cc
Create Date: 2025-06-25 19:00:31.418210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '15d268785937'
down_revision: Union[str, None] = 'd3aa437189cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrainement')
    op.drop_index(op.f('ix_vehicules_id'), table_name='vehicules')
    op.drop_index(op.f('numero_plaque'), table_name='vehicules')
    op.drop_table('vehicules')
    op.add_column('personnes', sa.Column('sex', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'personnes', ['sex'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personnes', type_='unique')
    op.drop_column('personnes', 'sex')
    op.create_table('vehicules',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('couleur', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('numero_plaque', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('marque', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('modele', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('annee', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('chauffeur_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['chauffeurs.id'], name=op.f('vehicules_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('numero_plaque'), 'vehicules', ['numero_plaque'], unique=True)
    op.create_index(op.f('ix_vehicules_id'), 'vehicules', ['id'], unique=False)
    op.create_table('entrainement',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('model_data', sa.BLOB(), nullable=False),
    sa.Column('image_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('entrainement_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
