"""ajout url image of history model pro1

Revision ID: 16724f2e7ab6
Revises: e5a8827aee53
Create Date: 2025-08-01 09:59:13.435775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '16724f2e7ab6'
down_revision: Union[str, None] = 'e5a8827aee53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historiques', 'url_img')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historiques', sa.Column('url_img', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
