"""tester la reconnaissance faciale et alcool 

Revision ID: 1fa68724a5aa
Revises: b86c14c90331
Create Date: 2025-07-25 08:08:53.541529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa68724a5aa'
down_revision: Union[str, None] = 'b86c14c90331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alcool_test_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datte', sa.DateTime(), nullable=False),
    sa.Column('valeur', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('face_test_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datte', sa.DateTime(), nullable=False),
    sa.Column('valeur', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_test_model')
    op.drop_table('alcool_test_model')
    # ### end Alembic commands ###
