"""ajout url image of history model

Revision ID: 2fa92f016899
Revises: c5c59101bbb7
Create Date: 2025-08-01 09:14:16.765117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa92f016899'
down_revision: Union[str, None] = 'c5c59101bbb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historiques', sa.Column('url_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historiques', 'url_image')
    # ### end Alembic commands ###
