"""mis a jour

Revision ID: 364572e6949f
Revises: ed5680c8bd57
Create Date: 2025-08-07 17:42:23.226874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '364572e6949f'
down_revision: Union[str, None] = 'ed5680c8bd57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historiques', 'alcool_value',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Float(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historiques', 'alcool_value',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
