"""mis a jour test history modele

Revision ID: 4a9ac2a0bb87
Revises: ede7e430da93
Create Date: 2025-07-29 07:22:04.717682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a9ac2a0bb87'
down_revision: Union[str, None] = 'ede7e430da93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historiques', 'alcool_value',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historiques', 'alcool_value',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
