"""Nouvelle migration2

Revision ID: 5248eea8f48a
Revises: d109e3912d18
Create Date: 2025-04-27 08:48:15.091692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5248eea8f48a'
down_revision: Union[str, None] = 'd109e3912d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chauffeurs', sa.Column('numero_permis', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'chauffeurs', ['numero_permis'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chauffeurs', type_='unique')
    op.drop_column('chauffeurs', 'numero_permis')
    # ### end Alembic commands ###
