"""mis a jour de l'historique

Revision ID: 6bdadde65c48
Revises: 7ebd02587d9d
Create Date: 2025-05-09 19:23:51.826198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6bdadde65c48'
down_revision: Union[str, None] = '7ebd02587d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historiques', 'commentaire')
    op.drop_column('historiques', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historiques', sa.Column('result', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('historiques', sa.Column('commentaire', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
