"""ajout de l'entrainement de l'image

Revision ID: 7ebd02587d9d
Revises: 5fbd343c503a
Create Date: 2025-04-30 19:16:56.857664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebd02587d9d'
down_revision: Union[str, None] = '5fbd343c503a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrainement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_data', sa.LargeBinary(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrainement')
    # ### end Alembic commands ###
