"""mis a jour du model administrateur

Revision ID: a0ce3c980398
Revises: c4e23591ccda
Create Date: 2025-07-01 10:43:33.187624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ce3c980398'
down_revision: Union[str, None] = 'c4e23591ccda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_administrateurs_id'), table_name='administrateurs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_administrateurs_id'), 'administrateurs', ['id'], unique=False)
    # ### end Alembic commands ###
