"""init data

Revision ID: a326bc687985
Revises: 
Create Date: 2025-04-25 18:52:09.677005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a326bc687985'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('postnom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_personnes_id'), 'personnes', ['id'], unique=False)
    op.create_table('administrateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('super_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['personnes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chauffeurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_permis', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['personnes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_permis')
    )
    op.create_table('historiques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chauffeur_id', sa.Integer(), nullable=False),
    sa.Column('jour_heure', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['chauffeurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historiques_id'), 'historiques', ['id'], unique=False)
    op.create_table('vehicules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couleur', sa.String(length=50), nullable=True),
    sa.Column('numero_plaque', sa.String(length=50), nullable=False),
    sa.Column('marque', sa.String(length=50), nullable=False),
    sa.Column('modele', sa.String(length=50), nullable=True),
    sa.Column('annee', sa.Integer(), nullable=True),
    sa.Column('chauffeur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['chauffeurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_plaque')
    )
    op.create_index(op.f('ix_vehicules_id'), 'vehicules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicules_id'), table_name='vehicules')
    op.drop_table('vehicules')
    op.drop_index(op.f('ix_historiques_id'), table_name='historiques')
    op.drop_table('historiques')
    op.drop_table('chauffeurs')
    op.drop_table('administrateurs')
    op.drop_index(op.f('ix_personnes_id'), table_name='personnes')
    op.drop_table('personnes')
    # ### end Alembic commands ###
