"""mis a jour de l'administrateur

Revision ID: afbdd783ad82
Revises: 6bdadde65c48
Create Date: 2025-05-10 09:15:48.789026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afbdd783ad82'
down_revision: Union[str, None] = '6bdadde65c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('administrateurs_ibfk_1', 'administrateurs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('administrateurs_ibfk_1', 'administrateurs', 'personnes', ['id'], ['id'])
    # ### end Alembic commands ###
