"""Relation entre image et historique

Revision ID: b86c14c90331
Revises: cf32a6b8fe63
Create Date: 2025-07-24 09:29:45.378249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86c14c90331'
down_revision: Union[str, None] = 'cf32a6b8fe63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historiques', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'historiques', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'historiques', type_='foreignkey')
    op.drop_column('historiques', 'image_id')
    # ### end Alembic commands ###
