"""tester mis a jour 

Revision ID: baf72422c509
Revises: 1fa68724a5aa
Create Date: 2025-07-25 08:21:36.259790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'baf72422c509'
down_revision: Union[str, None] = '1fa68724a5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alcool_test_model_id'), 'alcool_test_model', ['id'], unique=False)
    op.add_column('face_test_model', sa.Column('chauffeur_id', sa.Integer(), nullable=False))
    op.add_column('face_test_model', sa.Column('event_type', sa.String(length=255), nullable=False))
    op.add_column('face_test_model', sa.Column('person_info', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_face_test_model_id'), 'face_test_model', ['id'], unique=False)
    op.create_foreign_key(None, 'face_test_model', 'chauffeurs', ['chauffeur_id'], ['id'])
    op.drop_column('face_test_model', 'valeur')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_test_model', sa.Column('valeur', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'face_test_model', type_='foreignkey')
    op.drop_index(op.f('ix_face_test_model_id'), table_name='face_test_model')
    op.drop_column('face_test_model', 'person_info')
    op.drop_column('face_test_model', 'event_type')
    op.drop_column('face_test_model', 'chauffeur_id')
    op.drop_index(op.f('ix_alcool_test_model_id'), table_name='alcool_test_model')
    # ### end Alembic commands ###
