"""mis a jour du model administrateur

Revision ID: c4e23591ccda
Revises: 15d268785937
Create Date: 2025-07-01 10:38:23.515359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e23591ccda'
down_revision: Union[str, None] = '15d268785937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_administrateurs_id'), 'administrateurs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_administrateurs_id'), table_name='administrateurs')
    # ### end Alembic commands ###
