"""mis a jour de modele historique

Revision ID: c5c59101bbb7
Revises: 4a9ac2a0bb87
Create Date: 2025-07-31 20:22:42.074695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c5c59101bbb7'
down_revision: Union[str, None] = '4a9ac2a0bb87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historiques', 'event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historiques', sa.Column('event_type', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
