"""correction de model personne

Revision ID: c62752a6ae31
Revises: 16724f2e7ab6
Create Date: 2025-08-02 10:37:54.303305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c62752a6ae31'
down_revision: Union[str, None] = '16724f2e7ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personnes', 'sex',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.drop_index(op.f('sex'), table_name='personnes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('sex'), 'personnes', ['sex'], unique=True)
    op.alter_column('personnes', 'sex',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
