"""Nouvelle migration2

Revision ID: d109e3912d18
Revises: 506f0299ceae
Create Date: 2025-04-26 21:57:18.480896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd109e3912d18'
down_revision: Union[str, None] = '506f0299ceae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('numero_permis', table_name='chauffeurs')
    op.drop_column('chauffeurs', 'numero_permis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chauffeurs', sa.Column('numero_permis', mysql.VARCHAR(length=50), nullable=False))
    op.create_index('numero_permis', 'chauffeurs', ['numero_permis'], unique=True)
    # ### end Alembic commands ###
