"""ajout url image of history model pro

Revision ID: e5a8827aee53
Revises: 2fa92f016899
Create Date: 2025-08-01 09:23:35.851884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e5a8827aee53'
down_revision: Union[str, None] = '2fa92f016899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historiques', sa.Column('url_img', sa.String(length=255), nullable=True))
    op.drop_column('historiques', 'url_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historiques', sa.Column('url_image', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('historiques', 'url_img')
    # ### end Alembic commands ###
