"""initialisation propre

Revision ID: ed5680c8bd57
Revises: 
Create Date: 2025-08-06 10:04:10.482135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ed5680c8bd57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historiques', 'alcool_value',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historiques', 'alcool_value',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
