"""tester mis a jour32 

Revision ID: ede7e430da93
Revises: 26c77c2dcfee
Create Date: 2025-07-28 07:22:14.637668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ede7e430da93'
down_revision: Union[str, None] = '26c77c2dcfee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_test_model_id'), table_name='face_test_model')
    op.drop_table('face_test_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_test_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('datte', mysql.DATETIME(), nullable=False),
    sa.Column('chauffeur_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('event_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('person_info', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['chauffeurs.id'], name=op.f('face_test_model_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_face_test_model_id'), 'face_test_model', ['id'], unique=False)
    # ### end Alembic commands ###
