"""mis a jour de la table de test

Revision ID: fe1726c7e67d
Revises: 364572e6949f
Create Date: 2025-08-08 08:51:23.624937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fe1726c7e67d'
down_revision: Union[str, None] = '364572e6949f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alcool_test_model', 'valeur',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alcool_test_model', 'valeur',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
